### ISSUE TITLE
Difference bw 02.1.1 here and in Poedit 3.2.2

### ISSUE THREAD

**Issue by bovirus** [vslavik/gettext-tools-windows#10]
@vslavik 

What are the differences bewtween Getetxt tools 0.21.1 available here as package in Github (version 0.21.1 - files dated 18.11.2022) and same files included in Poedit 3.2.2 in \GetTetxtTools\bin (version 0.21- files dated 01.12.2022)?

**Comment by vslavik** [comment]
This is an issue tracker, not a satisfy-your-idle-curiosity question forum. You have the code of both at your disposal, you can answer your own question instead of lazily wasting others' time.
