### ISSUE TITLE
msgfmt.exe forced sets charset to UTF-8 value

### ISSUE THREAD

**Issue by RestorerZ** [vslavik/gettext-tools-windows#15]
When compiling a PO file into binary format, the value of the "charset" field is forcibly set to UTF-8, regardless of which value is set in the po file.
This behavior has been observed since version 0.22. Version 0.21.1 correctly handles the "charset" value.

**Comment by vslavik** [comment]
This is not not the place to report GNU gettext issues (did you even read the README?).

As anybody can trivially check themselves, the upstream change appears intentional: https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=commit;h=5412a4f79929004cb6db15d545e07dc953330e8d

**Comment by RestorerZ** [comment]
I'm working with GNU gettext tools for Windows, that's why I'm reporting here.
Thank you for informing me what the problem is.
I'll try to be more attentive next time.

**Comment by vslavik** [comment]
> I'm working with GNU gettext tools for Windows, that's why I'm reporting here.

You seem to have some curious difficulty with the sentence "This is an unofficial build of GNU gettext tools for Windows."...
