### ISSUE TITLE
Multiple Windows repositories... why?

### ISSUE THREAD

**Issue by mlocati** [vslavik/gettext-tools-windows#2]
Hi Václav,

I'm writing here to let you know that I grabbed your (smart) `gettextioencoding.patch` patch.

You can find my repository here: https://github.com/mlocati/gettext-iconv-windows (after some work, I managed to compile the [very latest version](https://github.com/mlocati/gettext-iconv-windows/releases/tag/v0.19.8.1-v1.14)).

I'm using a slightly different approach than your: I cross-compile under Ubuntu (using the great [mxe](http://mxe.cc/)) - that's in order to have a quite reproducible environment (virtual machines power :wink:).
BTW the result is quite the same, so, what about having just one repository for the Windows binaries of the gettext tools?

Best regards,
Michele

**Comment by vslavik** [comment]
> I'm writing here to let you know that I grabbed your (smart) gettextioencoding.patch patch.

The polite/well-behaved thing to do would be to use `git commit --author` when lifting another author’s commit in order to properly attribute the changes (best, because that’s what git is _for_), or at least adding an attribution note (not ideal, but OK). Appropriating the code under your own name is not very nice :-(

> BTW the result is quite the same, so, what about having just one repository for the Windows binaries of the gettext tools?

You’re welcome to submit reasonable PRs to that effect. As for the question in $subject, that’s for you to answer, I don’t know why you duplicated this (check the 1st commits) either ;)

Closing as not-an-issue, but feel free to continue commenting or talking over email.

**Comment by mlocati** [comment]
> The polite/well-behaved thing to do would be to use git commit --author when lifting another author’s commit in order to properly attribute the changes (best, because that’s what git is for), or at least adding an attribution note (not ideal, but OK). Appropriating the code under your own name is not very nice :-(

You're absolutely right. I added you to the newly created credits section in the readme file: https://github.com/mlocati/gettext-iconv-windows/commit/f8765150024d1d1d8dd78271dbb7a3357bdc0bc6

> You’re welcome to submit reasonable PRs to that effect

I don't think I could create PR on your repository: as I said I adopted a a completely different approach, and I've had many problems having MinGW on Windows to compile the 4 versions I currently support (32/64 bits & shared/static) - well, 3 at the moments since 32-bit shared [gives me problems](https://savannah.gnu.org/bugs/?48405).

So, let's close this discussion and continue having both repositories.

**Comment by vslavik** [comment]
> I don't think I could create PR on your repository: as I said I adopted a a completely different approach, 

Makes one wonder what the purpose of this issue was, then — none, it would seem.

**Comment by mlocati** [comment]
> > I don't think I could create PR on your repository: as I said I adopted a a completely different approach,
> 
> Makes one wonder what the purpose of this issue was, then — none, it would seem.

As I initially said, the purpose was to have a unique repository, neither mine not your but by both of us, to avoid duplicating the maintenance efforts.

But it seems it's not the case.
