### ISSUE TITLE
I think the path is being stored in $env:Path incorrectly

### ISSUE THREAD

**Issue by D-Bullock** [vslavik/gettext-tools-windows#6]
Running  $env:Path gives me 

> C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Office1\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code Insiders\bin;C:\Program Files\TortoiseGit\bin;C:\Users\Office1\AppData\Local\Microsoft\WindowsApps;C:\Users\Office1\AppData\Roaming\npm;C:\Users\Office1\AppData\Local\Programs\Fiddler;C:\Users\Office1\.nuget\packages\ngettext.wpf\1.0.17-alpha\tools;C:\Users\Office1\.nuget\packages\gettext.tools\0.19.8.1\tools

I think it should be 
....;C:\Users\Office1\.nuget\packages\gettext.tools\0.19.8.1\tools\\**bin**

**Comment by vslavik** [comment]
> I think it should be

If you know what to do, submit a PR, not an issue — a good rule of thumb for participating in any OSS project. However, the relevant code (330bcc382538f17dfc4e2494a82d8e4d2bb1a9fa) seems to do the right thing. Also, it wasn't released as a nuget update yet, which leads me to believe you're complaining about something that wasn't expected to work before and that is already fixed on `master`.

If you think I'm wrong, please [provide more details](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
