### ISSUE TITLE
[feature] Provide an installer for precompiled binaries on Windows.

### ISSUE THREAD

**Issue by hwhsu1231** [vslavik/gettext-tools-windows#8]
### Feature Request

Provide an installer for precompiled binaries on Windows.

An additional benefit of doing so is that we might be able to use [winget-cli](https://github.com/microsoft/winget-cli) to install your compiled gettext on Windows.

For example, running the following command:

```cmd
winget install VaclavSlavik.GetText
```

**Comment by hwhsu1231** [comment]
Although winget already supports to install [`GnuWin32.GetText`](https://github.com/microsoft/winget-pkgs/pull/97631) package, its latest version stopped at version `0.14.4`.

```cmd
C:\Users\hwhsu1231>winget search gettext
名稱              識別碼           版本   相符             來源
-----------------------------------------------------------------
GnuWin32: GetText GnuWin32.GetText 0.14.4 Moniker: gettext winget
```

**Comment by vslavik** [comment]
I'm not going to do that, sorry.
