### ISSUE TITLE
Build of Windows "static" gettext tool version

### ISSUE THREAD

**Issue by bovirus** [vslavik/gettext-tools-windows#9]
@vslavik 

Thanks a lot for your 0.21.1 build for windows.
Is it right that your versions seems version 0.21.1 64bit shared (with shared .dll library)?

Could you please consider to add also a build of w64bit "static" version with only exe file that not require .dll files?

Thanks.

**Comment by bovirus** [comment]
Why not planned?

I asked to add not to replace.
Or if you can pelase explain me how can do using your build.

Thanks.

**Comment by vslavik** [comment]
You're acting entitled and inappropriate. If you want to do some changes, submit a PR or fork. You don't get to "ask" for things in this entitled rude manner.
